export const HTTP_STATUSES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
}

export const HTTP_MESSAGES = {
  [HTTP_STATUSES.OK]: 'OK',
  [HTTP_STATUSES.CREATED]: 'CREATED',
  [HTTP_STATUSES.ACCEPTED]: 'ACCEPTED',
  [HTTP_STATUSES.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [HTTP_STATUSES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [HTTP_STATUSES.UNAUTHORIZED]: 'Unauthorized',
  [HTTP_STATUSES.FORBIDDEN]: 'Forbidden',
  [HTTP_STATUSES.BAD_REQUEST]: 'Bad Request',
  [HTTP_STATUSES.MISSING_PARAMETERS]: 'Missing parameters',
  [HTTP_STATUSES.INVALID_INPUT]: 'Invalid input',
  [HTTP_STATUSES.SERVICE_UNAVAILABLE]: 'Servuce unavailable'
}
